version = 0.1
[default.deploy.parameters]
stack_name = "cloud-architecture-ca1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1baj3dbg2tgxt"
s3_prefix = "cloud-architecture-ca1"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
