AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-architecture-ca1

  Sample SAM Template for cloud-architecture-ca1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  RouterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: order_router/
      Handler: order_router.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt InputQueue.Arn
            BatchSize: 10
      Policies: 
        - CloudFormationDescribeStacksPolicy: {}
        - SQSSendMessagePolicy:
            QueueName: "store-*"
        - DynamoDBWritePolicy:
            TableName: !Ref TableItems
      Environment:
        Variables:
          STACK_NAME: !Ref AWS::StackName

  InputQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: input-queue
  
  OutputStore1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: store-1
  
  OutputStore2:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: store-2
  
  OutputStore3:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: store-3

  TableItems:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: orderId
          AttributeType: N
        - AttributeName: itemCode
          AttributeType: S
      KeySchema: 
        - AttributeName: orderId
          KeyType: HASH
        - AttributeName: itemCode
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:

  StackArn:
    Description: "Stack ARN"
    Value: !Ref AWS::StackId
  
  StackName:
    Description: "Stack Name"
    Value: !Ref AWS::StackName

  RouterFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RouterFunction.Arn

  RouterFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RouterFunctionRole.Arn
  
  InputQueueUrl:
    Description: "Input Queue URL"
    Value: !Ref InputQueue
  
  OutputQueuesUrl:
    Description: "Output Queues URLs"
    # Dict number => url
    Value: !Sub
      - '{"1": "${store1}", "2": "${store2}", "3": "${store3}"}'
      - store1: !Ref OutputStore1
        store2: !Ref OutputStore2
        store3: !Ref OutputStore3
  
  TableItems:
    Description: "Table Items"
    Value: !Ref TableItems
